### ISSUE TITLE
TilePic and UniversalViewer rotate images based off original exif rotation data not current file state

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/providence#1134]
- CollectiveAccess 1.7.13
- GraphicsMagick 1.3.36
- gmagick 2.0.6 RC1

exif image rotation issue reported in https://collectiveaccess.atlassian.net/jira/software/c/projects/PROV/issues/PROV-2887 appears to still be an issue. issue now shows up in Opera as well (webkit based now).

will try rolling back GraphicsMagick version to 1.3.33

**Comment by 0nobody0** [comment]
1. the rotation problem continues to occur with GraphicsMagick (GM) 1.3.33 and 1.3.31 when using the gmagick (gm) pecl extension - the following combinations were tested:
a. GM 1.3.36 and gm 2.0,6 RC1
b. GM 1.3.33 and gm 2.0.6 RC1
c. GM 1.3.33 and gm 2.0.5 RC1
d. GM 1.3.33 and gm 2.0.0 RC1
e. GM 1.3.31 and gm 2.0.5 RC1

2. the rotation problem does not occur when using GraphicsMagick 1.3.31, 1.3.33 or 1.3.36 when the gmagick pecl extension is uninstalled. however import times are drastically increased (from 1-3 seconds per image to 30-60 seconds per image)

3. on another server (centos 7) running ca 1.7.8 w/ GraphicsMagick 1.3.31 and gmagick 2.0.5 this problem does not occur. will try rolling back and testing previous ca versions.

**Comment by collectiveaccess** [comment]
Can you try the develop code? There are fixes for this, but they have not been added to 1.7.x.

**Comment by 0nobody0** [comment]
sure - getting the following error when trying to access the install page on the develop branch:

`Fatal error: Uncaught Error: Call to undefined function caGetLoginLogo() in /usr/share/nginx/html/providencedev/themes/default/views/system/configuration_error_html.php:47 Stack trace: #0 /usr/share/nginx/html/providencedev/app/helpers/requestHelpers.php(147): require_once() #1 /usr/share/nginx/html/providencedev/app/helpers/post-setup.php(319): caCheckVendorLibraries() #2 /usr/share/nginx/html/providencedev/setup.php(221): require('/usr/share/ngin...') #3 /usr/share/nginx/html/providencedev/install/index.php(45): require_once('/usr/share/ngin...') #4 {main} thrown in /usr/share/nginx/html/providencedev/themes/default/views/system/configuration_error_html.php on line 47`

- nginx 1.14.1-9
- mariadb 10.5.12-1
- php 7.4.23-1

**Comment by 0nobody0** [comment]
got past the above error by removing line 47 from /themes/default/views/system/configuration_error_html.php

clicking the link to install vendor libraries ended with the following error but seemed to work - will continue setup testing for original rotation issue

```
Warning: require_once(../app/helpers/configurationHelpers.php): failed to open stream: No such file or directory in /usr/share/nginx/html/providencedev/install/index.php on line 46

Fatal error: require_once(): Failed opening required '../app/helpers/configurationHelpers.php' (include_path='/usr/share/nginx/html/providencedev/vendor/magento/zendframework1/library:/usr/share/nginx/html/providencedev/vendor/pear/pear_exception:/usr/share/nginx/html/providencedev/vendor/pear/file_marc:/usr/share/nginx/html/providencedev/vendor/pear/console_getopt:/usr/share/nginx/html/providencedev/vendor/pear/pear-core-minimal/src:/usr/share/nginx/html/providencedev/vendor/pear/archive_tar:/usr/share/nginx/html/providencedev/app/lib:/usr/share/nginx/html/providencedev/app/models:.:/usr/share/pear:/usr/share/php') in /usr/share/nginx/html/providencedev/install/index.php on line 46
```

**Comment by collectiveaccess** [comment]
It looks like you're missing files. Does app/helpers/configurationHelpers.php exist? It should.

**Comment by 0nobody0** [comment]
yes it's there

**Comment by collectiveaccess** [comment]
Maybe it's an nginx thing. Will have to try it.

**Comment by 0nobody0** [comment]
ok - the libraries appeared to have installed fine despite the error. just finished a test import and the photo rotation is confirmed fixed on the develop branch, using the original GraphicsMagick 1.3.36 and gmagick 2.0.6 RC1 . many thanks

**Comment by 0nobody0** [comment]
> Can you try the develop code? There are fixes for this, but they have not been added to 1.7.x.

just finished another batch import with the develop code and unfortunately seeing the rotation issue again, however much less often. can send example image files if that is of use.

**Comment by 0nobody0** [comment]
going to strip exif data from the images before importing as a workaround for now

**Comment by 0nobody0** [comment]
> ok - the libraries appeared to have installed fine despite the error. just finished a test import and the photo rotation is confirmed fixed on the develop branch, using the original GraphicsMagick 1.3.36 and gmagick 2.0.6 RC1 . many thanks

please ignore the quoted post, the closure of this ticket, and the following comments. i mixed up the test images i was referring to and it turns out there was never a change in how the images were being processed - all images with exif rotation continue to show the same original problem on the release and develop branch.

**Comment by 0nobody0** [comment]
just did some further testing on a server with a providence 1.7.8 install that does not show this issue. did a fresh providence develop branch and the rotation issue occurs.

- MySQL 5.7.30-1 (mysql57-community)
- nginx 1.1.14.1-9
- php 7.2.11-2
- GraphicsMagick 1.3.31

**Comment by collectiveaccess** [comment]
Can you send me a few images that are causing problems?

**Comment by 0nobody0** [comment]
sure - just emailed. thanks
