### ISSUE TITLE
History Tracking Throwing fatal error

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1484]
I have discovered (dev/php8) that a history tracking chronology and current contents aren't working as expected.

Everything is ok until you upload the location, then it throws the following error:

```
2023/08/22 12:15:40 [error] 14703#14703: *33 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Illegal offset type in /var/www/providence/app/models/ca_editor_uis.php:1079
Stack trace:
#0 /var/www/providence/app/models/ca_editor_uis.php(369): ca_editor_uis::getAvailableUIs()
#1 /var/www/providence/themes/default/views/bundles/history_tracking_chronology.php(297): ca_editor_uis::loadDefaultUI()
#2 /var/www/providence/app/lib/View.php(329): require('...')
#3 /var/www/providence/app/lib/View.php(297): View->_render()
#4 /var/www/providence/app/lib/HistoryTrackingCurrentValueTrait.php(2383): View->render()
#5 /var/www/providence/app/lib/BundlableLabelableBaseModelWithAttributes.php(2051): ca_objects->getHistoryTrackingChronologyHTMLFormBundle()
#6 /var/www/providence/app/lib/BundlableLabelableBaseModelWithAttributes.php(2923): BundlableLabelableBaseModelWithAttributes->getBundleFormHTML()
#7 /var/www/providence/themes/default/views/editor/objects/screen_html.php(60): BundlableLabelableBaseModelWithAttributes->getBundleFormHTMLForScreen()
#8 /va" while reading response header from upstream, client: 203.217.8.159, server: example.com, request: "GET /ca/editor/objects/ObjectEditor/Edit/Screen53/object_id/27 HTTP/1.1"
```

This error comes up everytime the screen with the history tracking chronology on it is loaded, only if there is a location that has been added.

If I go tot he location that was added, the object is not showing in the current content.

I've double checked the history tracking policy and cut it down to the very bare minimum

**Comment by Monica-Wood** [comment]
Switched over to php 7.4 and this is now just a 'warning' 
`Illegal offset type [/var/www/providence/app/models/ca_editor_uis.php:1079] `

**Comment by Monica-Wood** [comment]
Thank you :)
