### ISSUE TITLE
/dev/php8 caUtils load-export-mapping

### ISSUE THREAD

**Issue by antonio-cassano** [collectiveaccess/providence#1633]
Hi,
when I try to load export mapping from server by caUtils I get this PHP Fatal error:

[root@dv-ap1-new-php8-cabe-cabe cabe]# /data/www/html/cola/support/bin/caUtils load-export-mapping -f /cabe/METS_ECOMIC.xlsx
CollectiveAccess 2.0 (197/GIT) Utilities
(c) 2013-2023 Whirl-i-Gig

PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /data/www/html/cola/app/models/ca_data_exporters.php:2362
Stack trace:
#0 /data/www/html/cola/app/lib/Utils/CLIUtils/ImportExport.php(569): ca_data_exporters::loadExporterFromFile()
#1 /data/www/html/cola/support/bin/caUtils(172): CLIUtils::load_export_mapping()
#2 {main}
  thrown in /data/www/html/cola/app/models/ca_data_exporters.php on line 2362

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /data/www/html/cola/app/models/ca_data_exporters.php:2362
Stack trace:
#0 /data/www/html/cola/app/lib/Utils/CLIUtils/ImportExport.php(569): ca_data_exporters::loadExporterFromFile()
#1 /data/www/html/cola/support/bin/caUtils(172): CLIUtils::load_export_mapping()
#2 {main}
  thrown in /data/www/html/cola/app/models/ca_data_exporters.php on line 2362
[root@dv-ap1-new-php8-cabe-cabe cabe]# ^C

**Comment by collectiveaccess** [comment]
Just pushed a fix for this.
