### ISSUE TITLE
ElasticSearch indexing fatal error

### ISSUE THREAD

**Issue by kehh** [collectiveaccess/providence#792]
I'm currently getting a fatal error that seems to have been introduced in recent hierarchical indexing changes:
```

Done! [Indexing for list items, storage locations, relationship types, objects, occurrences, user groups, places, entities, object representations, loans, users, object lots, object checkouts, set items, comments, tags, movements, tours, tour stops, sets, collections took 20 seconds]
Note that if you're using an external search service like ElasticSearch, the data may only now be sent to the actual service because it was buffered until now. So you still might have to wait a while for the script to finish.
[20-Jan-2021 12:26:47 Australia/Hobart] PHP Fatal error:  Uncaught ApplicationException: Indexing error [illegal_argument_exception]: mapper [ca_object_labels/name_content_ids] of different type, current_type [text], merged_type [keyword] in /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php:671
Stack trace:
#0 /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php(357): WLPlugSearchEngineElasticSearch->flushContentBuffer()
#1 /var/www/html/tas-providence/support/bin/caUtils(170): WLPlugSearchEngineElasticSearch->__destruct()
#2 {main}
  thrown in /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php on line 671

Fatal error: Uncaught ApplicationException: Indexing error [illegal_argument_exception]: mapper [ca_object_labels/name_content_ids] of different type, current_type [text], merged_type [keyword] in /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php:671
Stack trace:
#0 /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php(357): WLPlugSearchEngineElasticSearch->flushContentBuffer()
#1 /var/www/html/tas-providence/support/bin/caUtils(170): WLPlugSearchEngineElasticSearch->__destruct()
#2 {main}
  thrown in /var/www/html/tas-providence/app/lib/Plugins/SearchEngine/ElasticSearch.php on line 671
```

It looks like ES is guessing the field types for `*_content_ids` fields and then getting new values that don't conform top this guessed type. I have a feeling it's somewhere in app/lib/Plugins/SearchEngine/ElasticSearch/Mapping.php

Using ES 6.x with the 6.x composer dependency.

**Comment by collectiveaccess** [comment]
Have you tried with 7.x?

**Comment by kehh** [comment]
I've been getting this in 5.x, 6.x and 7.x and the above fix resolves it in all of them.

**Comment by collectiveaccess** [comment]
Perfect.
